ImranR98/Obtainium

- lib/custom_errors.dart
- lib/main.dart
- lib/pages/settings.dart
- lib/providers/apps_provider.dart
- lib/providers/logs_provider.dart
- pubspec.lock
- pubspec.yaml
Logging is mainly just for the BG task and errors right now.
> Added basic logging

- lib/app_sources/apkmirror.dart
- lib/app_sources/fdroid.dart
- lib/app_sources/fdroidrepo.dart
- lib/app_sources/gitlab.dart
- lib/app_sources/mullvad.dart
- lib/app_sources/signal.dart
- lib/app_sources/sourceforge.dart
- lib/app_sources/steammobile.dart
- lib/main.dart
- lib/providers/source_provider.dart
- pubspec.yaml
> Track-only source bugfix +  better http errors

- lib/components/generated_form.dart
- lib/components/generated_form_modal.dart
- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/app.dart
- lib/pages/apps.dart
- lib/pages/settings.dart
- pubspec.lock
- pubspec.yaml
- App page is now scrollable (previously, overflowing items would just get clipped).
- Category selection UI is now available on Add App page and replaces the single-select dropdown on the Apps filter UI.
- Adding an existing category no longer overwrites it (thereby removing all Apps from that category).
- Selection count now visible on the deselect button on the Apps page.
- Other UI tweaks and bugfixes.
> UI improvements

- lib/components/generated_form.dart
- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/import_export.dart
- lib/providers/apps_provider.dart
- pubspec.yaml
- Added delay after Obtainium install prompt to avoid updating Obtainium before other Apps (#242).
- Fixed problems with generated forms not updating when fields change (#245).
- Search option no longer immediately adds the App, instead giving the user a chance to adjust the additional options first.
- URL selection modals (used for search and third-party imports) now let you tap the description text to select/deselect an entry (instead of just the checkbox).
> Bugfixes for #242 and #245 + Various UI Improvements

- README.md
Related to https://github.com/ImranR98/Obtainium/issues/30#issuecomment-1424249408
> Add installation badges

- assets/translations/de.json
- assets/translations/en.json
- assets/translations/hu.json
- assets/translations/it.json
- assets/translations/ja.json
- assets/translations/zh.json
- lib/custom_errors.dart
- lib/main.dart
- lib/pages/app.dart
- lib/providers/apps_provider.dart
- pubspec.yaml
> No longer blocking App ID changes in updates

- assets/translations/de.json
- assets/translations/en.json
- assets/translations/fa.json
- assets/translations/hu.json
- assets/translations/it.json
- assets/translations/ja.json
- assets/translations/zh.json
- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/app.dart
- lib/pages/apps.dart
- lib/pages/import_export.dart
- lib/pages/settings.dart
- lib/providers/apps_provider.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
- Added "URLs in File" import (#326)
- Unified version detection setting (#312)
- UI Bugfix (#325)
> Added "URLs in File" import (#326) + UI Improvements (#312, #325)

- lib/pages/app.dart
- lib/providers/apps_provider.dart
> Bugfix: "releaseDateAsVersion" resets to "noVersionDetection"

- assets/translations/de.json
- assets/translations/en.json
- assets/translations/fa.json
- assets/translations/fr.json
- assets/translations/hu.json
- assets/translations/it.json
- assets/translations/ja.json
- assets/translations/zh.json
- lib/components/generated_form.dart
- lib/main.dart
- lib/providers/source_provider.dart
- pubspec.yaml
Plus minor form switch UI fixes (overflow, spacing)
> Added simple APK try auto-select by CPU arch #436

- lib/app_sources/codeberg.dart
- lib/app_sources/github.dart
- lib/app_sources/gitlab.dart
- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/app.dart
- lib/pages/apps.dart
- lib/pages/import_export.dart
- lib/providers/apps_provider.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
- Bugfix: Ensure "Reset Install Status" button is enabled. Also show it on the App page when appropriate. #479
- Bugfix: Prevent range error during APK selection. #201
- Bugfix: Sort GitHub releases by release date before picking one. #478
- Code improvement: Remove redundant Codeberg code - reuse GitHub implementations instead.
- UI Improvement: Show App version in changelog dialog. #482
- UI Improvement: URL selection modal now uses radio buttons in single-select mode. #460
- UI Improvement: More adaptive column spacing in Apps list. #485
- Feature: "Fallback to older release" option for GitLab. #456
> Several bugfixes and minor UI improvements + GitLab fallback support

- assets/translations/pl.json
Consider using https://hosted.weblate.org to simplify the translation process.
> locale(pl): Update Polish translation

- assets/translations/zh.json
> Update Chinese translation

- assets/translations/de.json
translated some missing strings
> Update de.json - translate missing strings

- lib/app_sources/html.dart
Swap user agent with a chrome browser on Android
Should mitigate #709
> Update html user agent with a believable one

- lib/pages/app.dart
> Add back button to app detail page (#721)

- .github/workflows/android.yml
Simple script to make updates easier on you, you just need to give it the proper permissions by your GitHub Access Token, and add the signing keys to the secrets.
Solves #513
> Workflow to build and release

- lib/app_sources/fdroid.dart
Tested and working on my end very well for the examples mentioned in #946 and I also tried [FFShare](https://f-droid.org/packages/com.caydey.ffshare)
> Better version detection for F-Droid

- .github/workflows/release.yml
- android/app/build.gradle
I hope it will work since I did not test it.
> Small optimization

- lib/main.dart
- lib/pages/apps.dart
- lib/providers/apps_provider.dart
- pubspec.yaml
- Fix installed version bug when importing apps (#1179)
- Share button now shares Obtainium "protocol" links
> Fix installed version bug when importing apps (#1179), Share button now shares Obtainium "protocol" links

- lib/main.dart
- lib/providers/source_provider.dart
- pubspec.yaml
HTML intermediate link bugfix (#1211)
> HTML intermediate link bugfix (#1211)

- README.md
- lib/components/generated_form.dart
- lib/main.dart
- lib/providers/apps_provider.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
Removed Steam Source (existing apps auto-switched to HTML) (#1244) + Bugfixes
> Removed Steam Source (existing apps auto-switched to HTML) (#1244) + Bugfixes

- lib/app_sources/html.dart
- lib/main.dart
- pubspec.yaml
URL parsing bugfix for HTML source (#1253)
> URL parsing bugfix for HTML source (#1253)

- assets/translations/pt.json
- lib/app_sources/fdroid.dart
- lib/main.dart
- pubspec.yaml
- Add F-Droid changelogs (#1255)
- Fix corrupt pt.json (#1256)
> Add F-Droid changelogs (#1255), Fix corrupt pt.json (#1256)

- README.md
- lib/app_sources/apkcombo.dart
- lib/app_sources/apkmirror.dart
- lib/app_sources/apkpure.dart
- lib/app_sources/aptoide.dart
- lib/app_sources/codeberg.dart
- lib/app_sources/fdroid.dart
- lib/app_sources/github.dart
- lib/app_sources/gitlab.dart
- lib/app_sources/html.dart
- lib/app_sources/huaweiappgallery.dart
- lib/app_sources/izzyondroid.dart
- lib/app_sources/jenkins.dart
- lib/app_sources/mullvad.dart
- lib/app_sources/neutroncode.dart
- lib/app_sources/signal.dart
- lib/app_sources/sourceforge.dart
- lib/app_sources/sourcehut.dart
- lib/app_sources/steammobile.dart
- lib/app_sources/telegramapp.dart
- lib/app_sources/uptodown.dart
- lib/app_sources/vlc.dart
- lib/app_sources/whatsapp.dart
- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/import_export.dart
- lib/providers/settings_provider.dart
- lib/providers/source_provider.dart
- pubspec.yaml
- Multi-host support + add '.net' host to APKPure source (#1250)
- HTML link parsing bugfix (#1259)
- APKMirror version extraction bugfix (#1264)
> Multi-host support + add '.net' host to APKPure source (#1250), HTML link parsing bugfix (#1259), APKMirror version extraction bugfix (#1264)

- lib/app_sources/html.dart
- lib/components/generated_form.dart
- lib/main.dart
- pubspec.lock
- pubspec.yaml
- Fix form input issues (related to #1272)
- HTML Source bugfix (related to #1259)
> Fix form input issues (related to #1272), HTML Source bugfix (related to #1259)

- assets/translations/bs.json
- assets/translations/cs.json
- assets/translations/de.json
- assets/translations/en.json
- assets/translations/es.json
- assets/translations/fa.json
- assets/translations/fr.json
- assets/translations/hu.json
- assets/translations/it.json
- assets/translations/ja.json
- assets/translations/nl.json
- assets/translations/pl.json
- assets/translations/pt.json
- assets/translations/ru.json
- assets/translations/sv.json
- assets/translations/tr.json
- assets/translations/vi.json
- assets/translations/zh.json
- lib/main.dart
- lib/pages/apps.dart
- lib/providers/apps_provider.dart
- lib/providers/settings_provider.dart
- lib/providers/source_provider.dart
Allow entire app config to be shared as link (see https://github.com/ImranR98/apps.obtainium.imranr.dev/issues/5)
> Allow entire app config to be shared as link (see https://github.com/ImranR98/apps.obtainium.imranr.dev/issues/5)

- android/app/src/main/AndroidManifest.xml
- lib/app_sources/html.dart
- lib/app_sources/sourceforge.dart
- lib/providers/apps_provider.dart
- lib/providers/source_provider.dart
- Better support for SourceForge (#1352)
- Remove READ_EXTERNAL_STORAGE again (#1309) + fix typo
> Better support for SourceForge (#1352), Remove READ_EXTERNAL_STORAGE again (#1309) + fix typo

- assets/translations/de.json
Translation of the Note of the sources window
> Translation of the Note of the sources window

- README.md
> Add F-droid badge to README.md

- lib/app_sources/gitlab.dart
- lib/providers/apps_provider.dart
- pubspec.lock
- pubspec.yaml
* Add support for GitLab CI artifact links in releases (#1506)
* Improve load speed on return to foreground
> Add support for GitLab CI artifact links in releases (#1506), Improve load speed on return to foreground

- assets/translations/fr.json
> (following d8c805a + #1670) Undone a mistake

- README.md
- lib/app_sources/apkpure.dart
- lib/app_sources/html.dart
- lib/pages/apps.dart
- lib/providers/apps_provider.dart
- pubspec.lock
- pubspec.yaml
- APKPure: Filter releases by available architecture (#598)
- Use a more obvious icon (magnifying glass) for the "filter apps" button (#1762)
> APKPure: Filter releases by available architecture (#598), Use a more obvious icon (magnifying glass) for the "filter apps" button (#1762)

- lib/app_sources/apkpure.dart
- pubspec.lock
- pubspec.yaml
APKPure bugfix: Correctly extract APKs that are multi-arch but not universal
>  APKPure bugfix: Correctly extract APKs that are multi-arch but not universal

- README.md
- lib/app_sources/tencent.dart
- lib/pages/app.dart
- lib/pages/apps.dart
- lib/providers/apps_provider.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
- Add Tencent App Store (#1848)
- Enable icon caching (#1837)
> Add Tencent App Store (#1848), Enable icon caching (#1837)

- lib/main.dart
- pubspec.yaml
- Add Indonesian to language menu
> Add Indonesian to language menu

- lib/app_sources/sourcehut.dart
- pubspec.yaml
- Fix broken SourceHut source (#1864)
> Fix broken SourceHut source (#1864)

- assets/translations/id.json
This PR mostly centered to fix some wording and untranslated word after reviewing https://github.com/ImranR98/Obtainium/pull/1868
> Fix indonesian translation

- lib/app_sources/github.dart
- pubspec.yaml
Bugfix: GitHub fallback option was broken (#2032)
> Bugfix: GitHub fallback option was broken (#2032)

- README.md
- lib/app_sources/apkpure.dart
- lib/app_sources/telegramapp.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
- APKPure bugfix
- Restore "Telegram App" source (#2025)
> APKPure bugfix, Restore "Telegram App" source (#2025)

- .github/workflows/release.yml
- .gitignore
- .metadata
- analysis_options.yaml
- android/.gitignore
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/build.gradle
- android/gradle.properties
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- lib/pages/app.dart
- lib/pages/apps.dart
- pubspec.lock
- pubspec.yaml
- Upgrade to latest Flutter version (fix errors that were preventing this)
- Fix button highlight visibility on black theme (#2039)
> Upgrade to latest Flutter version (fix errors that were preventing this), Fix button highlight visibility on black theme (#2039)

- lib/pages/apps.dart
- pubspec.lock
- pubspec.yaml
- Fix categories UI bug (#2064)
- Fix how changelog quotes look in dark theme (#2065)
> Fix categories UI bug (#2064), Fix how changelog quotes look in dark theme (#2065)

- lib/pages/app.dart
Simple way to fix #2158, where all details are provided. A follow-up to #2163.
Not sure if that's not the absolutely inappropriate way of doing that, so a draft PR for now :)
> Possible fix for apps webpages opened twice with "Show Source webpage in App view"

- README.md
- assets/translations/en.json
- assets/translations/zh.json
- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/android/ru/full_description.txt
- lib/app_sources/coolapk.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
Close #532.
Works on my machine, I'll try to workaround its geo-blocking later, so you can test it yourself.
> Add CoolApk

- lib/app_sources/apkpure.dart
> allow apkpure links for apks with no variant list

- lib/app_sources/coolapk.dart
- lib/pages/add_app.dart
- lib/providers/source_provider.dart
I gave [this](https://github.com/ImranR98/Obtainium/pull/2269#issuecomment-2869128012) a try. Feel free to use it or close the PR and do it some other way if you prefer. Also, I'm not sure what's idiomatic for Dart formatting
> Add allowOverride app source option

- README.md
- assets/translations/en.json
- assets/translations/zh.json
- fastlane/metadata/android/en-US/full_description.txt
- fastlane/metadata/android/ru/full_description.txt
- lib/app_sources/vivoappstore.dart
- lib/providers/source_provider.dart
Add vivo App Store with search support. This will be useful for Chinese users.
Currently their apis used on the web (h5) version don't require any authentication. Don't know if it will change in the future.
> Add support for vivo App Store

- lib/app_sources/rustore.dart
- pubspec.yaml
- Attempt to fix RuStore charset bug (#2294)
> Attempt to fix RuStore charset bug (#2294)

- assets/translations/zh.json
- Translate new strings
- Correct inaccurate translations
- Other trivial improvements
> feat(i18n): Update Simplified Chinese translation

- assets/translations/ar.json
- assets/translations/bs.json
- assets/translations/ca.json
- assets/translations/cs.json
- assets/translations/da.json
- assets/translations/de.json
- assets/translations/en-EO.json
- assets/translations/en.json
- assets/translations/es.json
- assets/translations/fa.json
- assets/translations/fr.json
- assets/translations/hu.json
- assets/translations/id.json
- assets/translations/it.json
- assets/translations/ja.json
- assets/translations/ko.json
- assets/translations/ml.json
- assets/translations/nl.json
- assets/translations/pl.json
- assets/translations/pt-BR.json
- assets/translations/pt.json
- assets/translations/ru.json
- assets/translations/sv.json
- assets/translations/tr.json
- assets/translations/uk.json
- assets/translations/vi.json
- assets/translations/zh-Hant-TW.json
- assets/translations/zh.json
- lib/app_sources/html.dart
> feat: add option to match links outside <a> tags even if links in <a> tags are found

- assets/translations/pt.json
Some terms were in Portuguese from Brazil and others slightly incorrect. Fixed them to be Portuguese from Portugal/Europe.
> Refined translation terms

- lib/app_sources/github.dart
- pubspec.lock
- pubspec.yaml
Stop sending GitHub token if a "hubproxy" instance is in use
> Stop sending GitHub token if a "hubproxy" instance is in use
