- lib/app_sources/fdroid.dart
- lib/app_sources/github.dart
- lib/app_sources/gitlab.dart
- lib/app_sources/izzyondroid.dart
- lib/app_sources/mullvad.dart
- lib/app_sources/signal.dart
- lib/components/generated_form.dart
- lib/components/generated_form_modal.dart
- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/app.dart
- lib/pages/home.dart
- lib/pages/import_export.dart
- lib/pages/test_page.dart
- lib/providers/apps_provider.dart
- lib/providers/source_provider.dart
1. Added a `GeneratedForm` class to generate forms dynamically from a `List` of requirements.
2. Added `additionalDataFormItems` to the `AppSource` class to enable the user to specify Source-specific options on an App by App basis.
3. Added the followin Source-specific options for GitHub Apps:
1. Include pre-releases (`true` by default) - #18
2. Fall back on older releases if the latest release has no APKs (`true` by default) - #22
3. Filter releases by their titles using regular expressions - #20
4. Various bugfixes and tweaks (including for #17)
> Adds Source-specific options + other changes

- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/app.dart
- lib/pages/apps.dart
- lib/providers/apps_provider.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
Obtainium now uses real package names as IDs instead of internally-generated IDs. This allows it to detect whether Apps are already installed and mark them accordingly. When an App is uninstalled, it is also automatically marked as such in Obtainium. So the mark as installed/uninstalled buttons are no longer needed. Unfortunately, the real version number of an App may be different from the version string extracted from its Source, so a "mark as updated" button is still needed and remains.
Apps with "non-real" generated Apps may still exist due to being from previous versions of Obtainium or being imported (GitHub and URL imports also use these for convenience). These are automatically upgraded to the new format when they are installed for the first time.
WARNING: Since Obtainium …
> Real Package Names Used as IDs + App Icons (INCONVENIENT FOR PREVIOUS VERSION USERS)

- lib/app_sources/apkmirror.dart
- lib/app_sources/fdroid.dart
- lib/app_sources/fdroidrepo.dart
- lib/app_sources/github.dart
- lib/app_sources/gitlab.dart
- lib/app_sources/izzyondroid.dart
- lib/app_sources/mullvad.dart
- lib/app_sources/signal.dart
- lib/app_sources/sourceforge.dart
- lib/app_sources/steammobile.dart
- lib/components/generated_form.dart
- lib/components/generated_form_modal.dart
- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/app.dart
- lib/pages/apps.dart
- lib/pages/import_export.dart
- lib/pages/settings.dart
- lib/providers/apps_provider.dart
- lib/providers/settings_provider.dart
- lib/providers/source_provider.dart
- pubspec.yaml
Breaking `GeneratedFormItem` into sub-types will let us more easily implement specialized functionality for each type. This is being done in preparation for a "tags" input type to use with the categorization UI.
This PR also fixes a bug where the GitHub PAT input does not load the saved value.
> Broke `GeneratedFormItem` into sub-types + bugfix

- lib/app_sources/github.dart
- lib/main.dart
- lib/providers/apps_provider.dart
- pubspec.yaml
- Obtainium would skip installing APKs that had the same [`versionCode`](https://developer.android.com/studio/publish/versioning#versioningsettings) since this number should be different for each new build of an App.
- However, there are enough Apps that don't do this (#149, #219) so Obtainium now installs updates even if the `versionCode` has not changed.
- The GitHub release title filter has also been improved so that it filters by `tag_name` instead of `title` for releases with empty titles (as it seems like GitHub automatically displays the tag as the title in such cases).
> Same-versionCode Updates no Longer Skipped + 1 Other Bugfix

- README.md
- lib/app_sources/codeberg.dart
- lib/app_sources/html.dart
- lib/main.dart
- lib/pages/add_app.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
- Codeberg has an API very similar (almost identical) to GitHub's, and has been added as a Source with all the extra options that GitHub supports (search, older release fallback, pre-release filtering, and title filtering).
- A new "fallback" Source has been added for URLs that don't match any other Source. It looks for links to APKs on the provided page and grabs one, if any.
- Also increments version to `0.10.01 (2 new Sources warrants it I think).
> 2 New Sources: Codeberg and HTML Fallback

- .gitmodules
ATM, there is only one flutter app with the reproducible build on fdroid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12398
In order to get a reproducible build with flutter:
* flutter must be the exact same commit : that's why this PR set it as a git submodule (update the PATH afterward). [0]
* The full path to the project must be the same too. It is suggested to use /tmp/build : `ln -s $(pwd) /tmp/build ; cd /tmp/build`. Of course, if you want to use a github action for the build process, you won't even notice the path used :)
[0] Note: To fetch the current submodule code: `git submodule update` and to update it: `git submodule update --remote`
> Add flutter as a submodule for reproducible build

- lib/app_sources/mullvad.dart
- lib/components/generated_form.dart
- lib/main.dart
- lib/pages/add_app.dart
- lib/pages/app.dart
- lib/pages/apps.dart
- lib/pages/import_export.dart
- lib/providers/apps_provider.dart
- lib/providers/source_provider.dart
- pubspec.lock
- pubspec.yaml
1. Apps that don't have "standard" versioning formats now automatically stop using version detection. This will prevent users from having to learn about this feature and enable it manually.
- For such Apps, the "standard" version detection option is greyed out.
2. The Mullvad Source recently broke due to a slight change in their website design. This is now fixed.
- Mullvad also now provides an in-app changelog via their official GitHub repo.
3. Code has been refactored for readability (specifically the version detection code and UI code for most screens).
4. Minor UI tweaks and bugfixes.
> Version detection improvements, Mullvad web scraping fix and changelog addition, code readability improvements, general tweaks/bugfixes

- assets/translations/de.json
- assets/translations/en.json
- assets/translations/fa.json
- assets/translations/fr.json
- assets/translations/hu.json
- assets/translations/it.json
- assets/translations/ja.json
- assets/translations/zh.json
- lib/main.dart
- lib/pages/settings.dart
- lib/providers/settings_provider.dart
This PR adds a switch to enable a pure black (amoled) theme, works for both the Obtainium and the Material You theme.
closes #155
> Add an amoled black theme

- lib/providers/apps_provider.dart
This PR changes how Obtainium extracts zip files. Obtainium currently loads the entire zip file to memory, which will throw an out of memory error for large apps.
Testing has been hard for this given the time to download each 1-2GB app and possible further issues with how Obtainium handles OBB's/Multi-APK's in xapks. Although these apps no longer fail to install, I haven't yet had one successfully run, have it's expected app size, or have it's OBB's in android/obb/
So I'm putting this as a draft PR until it can be determined if my implementation is the issue or not.
> Fix out of memory error for large xapk's

- lib/providers/apps_provider.dart
Supports android versions below 11 and OS's with toggles (such as grapheneOS)
It's purported that apps with REQUEST_INSTALL_PACKAGES can access Android/obb [but that's either bugged or false](https://issuetracker.google.com/issues/254445476)
Android 11 and 12 has [a work around which is quite hacky](https://blog.esper.io/android-dessert-bites-28-file-manager-loophole-closed-73891524/), but if thats ok I can add support in another PR
Android API 34 has worked with MANAGE_EXTERNAL_STORAGE, but I'm not sure if this will still be the case in the final release of android 14 so I removed the code for it.
closes #622
> add OBB support

- lib/providers/apps_provider.dart
- pubspec.lock
- pubspec.yaml
PR #616 removed the need to load the zip file into memory, however the archive library itself also loads individual files into memory when writing. Considering that some xapk's are mainly comprised of a single obb file this is an issue.
Archive also suppresses any out of memory errors and writes the file but with zero bytes, giving no indication that it failed.
This PR replaces archive with the archive_flutter plugin, which will break files into blocks when writing.
> change archive library

- lib/app_sources/apkpure.dart
Related: #572
Pulls from both the standard url and the download page because the file type is on one and the change log is on the other.
Looked into adding support for fdroid, but `getAPKUrlsFromFDroidPackagesAPIResponse` is also used by izzyondroid and `FDroidRepo.getLatestAPKDetails` was never called while I was debugging.
> Add changelog for apkpure

- lib/providers/apps_provider.dart
Found when looking into #427
Wont link this PR to close as I'm not sure if these bugs are the same.
While checkUpdate waits on getApp, removeApps can remove the appID from the list and delete the json file. After getApp returns, checkUpdate will rewrite the json file.
This isn't an perfect fix as these functions can run at the same time. The only other fixes I can think of would be either refactoring practically all of apps_provider, or somehow synchronously calling getApp which would cause a massive delay whenever an app page is opened.
> fix race condition when checking updates

- lib/components/generated_form.dart
- lib/pages/settings.dart
- pubspec.lock
- pubspec.yaml
Love the app, I have switched from F-Droid to using Obtainium for all my FOSS android apps.
I tried organising by category but I kept getting different shades of green.
This PR makes category colors more accessible using a combination of the [HSLuv (Pastel)](https://pub.dev/documentation/hsluv/latest/hsluv/Hsluv-class.html) color space and incrementing by the [Golden Angle](https://en.wikipedia.org/wiki/Golden_angle).
I removed the randomness as it was causing some duplicate colors with the golden angle.
> Fix #397 Edit Category Colors & Accessible colors using HSLuv

- android/app/src/main/res/drawable/ic_launcher_foreground.xml
Android documentation [1] explicity specify that adaptive icons must be 108x108dp.
Having bigger Adaptive icons triggers a bug in Android 14 QPR1 that prevent to install apps from apk directly when the icons are bigger.
[1] https://developer.android.com/develop/ui/views/launch/icon_design_adaptive
> Resize adaptative icon to 108x108dp (#1142)

- assets/translations/bs.json
- assets/translations/de.json
- assets/translations/es.json
- assets/translations/fa.json
- assets/translations/fr.json
- assets/translations/hu.json
- assets/translations/ja.json
- assets/translations/nl.json
- assets/translations/pl.json
- assets/translations/sv.json
- assets/translations/tr.json
- assets/translations/vi.json
```
"installMethod": "Installation method",
"normal": "Normal",
"shizuku": "Shizuku",
"root": "Root",
"shizukuBinderNotFound": "Shizuku is not running",
```
were missing in some languages
> added missing strings in some languages, translated for DE

- lib/pages/app.dart
- lib/pages/apps.dart
- Bugfix: don't show 'Apps Updated' toast when nothing was updated (#1307)
- Disable app page buttons while app info is being updated
> Bugfix: don't show 'Apps Updated' toast when nothing was updated (#1307), Disable app page buttons while app info is being updated

- lib/app_sources/gitlab.dart
There occur issues if releases refer to external hosted .apk files. In some cases (e.g. Aurora Store) download is not possible because cloudflare protection gives "forbidden" error. This patch will add a "referer" header to the download request to pacify cloudflare protection service. 
Notice: In case of the `Aurora Store` project, you still need a `Gitlab API token`, to retrieve latest .apk release. Obtainium either retrieves .apk data from Gitlab API (token necessary) or from `tags`-page, which has no information about the latest .apk url.
Related to: #1397, #1389, #1384, #1382, #1381, #1380, #1359, #854, #785, #697
Tested with Android 14 in an emulated AVD.
> Solve issues with gitlab .apk files and cloudflare protection

- lib/app_sources/gitlab.dart
Obtainium 1.0.4 has two strategies to retrieve .apk information from Gitlab: This is either (a) by using the Gitlab API with a Private Access Token (PAT) or either (b) by using the tags-page of a repository. In some cases (e.g. Aurora Store) the tags-page does not have information about related .apk files, but the Gitlab API has (#1450, #1381, #1380).
This patch removes the tags-page as an information provider and simplifies the retrieval logic. As it turned out: Gitlab's REST API works without `Private Access Token` authentication for public repositories. So the `Private Access Token` is optional in case authentication is required.
Previous discussion: #1438 
Tested with `Android 14` on an emulated AVD
Notice: I haven't tested this patch with private repositories and/or private Gitlab …
> Improve gitlab .apk retrieval (#1450, #1381, #1380)

- assets/translations/fr.json
There's no "`e`" in the word "F-Droid" in French. Also, there's no "`ï`" in that word. F-Droid is not a translatable name, since it's just a software/product name.
> Fix 'F-Droid' translation' in fr.json

- lib/components/generated_form.dart
Closes https://github.com/ImranR98/Obtainium/issues/1530.
See issue for reproduction. The length of `widget.items` is one item longer than `formInputs`, it was causing a [RangeError](https://github.com/ImranR98/Obtainium/issues/1530#issuecomment-2043493700) when trying to access `formInputs[r]` and `r` was going to to `widget.items.length`:
```
I/flutter ( 1881): widget.items.length: 21
I/flutter ( 1881): formInputs.length: 20
```
> Fix out of bounds array access in GeneratedForm update

- android/app/src/main/AndroidManifest.xml
Fixes #1378
Instead of hardcoding the authority string, use the ${applicationId} to always make the provider unique.
> Use applicationId for provider authorities

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/xml/locales_config.xml
Hi!
I've manually enabled per-app langugage as per [android docs](https://developer.android.com/guide/topics/resources/app-languages#use-localeconfig) as flutter does not support it [yet](https://github.com/flutter/flutter/issues/109842)
> Enable per-app language, closes #1430

- lib/providers/apps_provider.dart
Make the exported applications' file more readable in case it is needed to be opened with a text editor.
> Format exported json

- assets/translations/bs.json
- assets/translations/cs.json
- assets/translations/da.json
- assets/translations/de.json
- assets/translations/en-EO.json
- assets/translations/en.json
- assets/translations/es.json
- assets/translations/fa.json
- assets/translations/fr.json
- assets/translations/hu.json
- assets/translations/id.json
- assets/translations/it.json
- assets/translations/ja.json
- assets/translations/nl.json
- assets/translations/pl.json
- assets/translations/pt.json
- assets/translations/ru.json
- assets/translations/sv.json
- assets/translations/tr.json
- assets/translations/uk.json
- assets/translations/vi.json
- assets/translations/zh-Hant-TW.json
- assets/translations/zh.json
- lib/pages/add_app.dart
**Resolves #1727**
This pull request introduces a new button labeled **"Community App Sources"** to the **AddAppPage**. When clicked, this button will open an external application with the URL: [https://apps.obtainium.imranr.dev/](https://apps.obtainium.imranr.dev/). Translations for the "Community App Sources" label have been included for multiple languages to ensure international support.
- Added a **"Community App Sources"** button on the **AddAppPage**
- Integrated translations for the button text across various languages
- Launched an external URL when the button is clicked
<details>
<summary>Dark Mode</summary>
</details>
<details>
<summary>Light Mode</summary>
</details>
> Add "Community App Sources" translation and button to Add App Screen

- android/app/build.gradle
- android/app/src/debug/res/values/string.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/res/values/string.xml
This permits the debug build to be installed side-by-side with the release/f-droid version so it's easier to debug without uninstalling/reinstalling constantly
> Allow installation of the debug build

- lib/pages/add_app.dart
- lib/providers/source_provider.dart
Add Custom App ID generally used for Track Only Sources like ApkMirror
> Add Custom app ID

- assets/translations/fr.json
- The previous correction was still too long, so I corrected it again.
- Line 317: "Configuration d'applis communautaire" changed by "Applis communautaires"
- translation suggested by @peternmuller
> Correction of long translations (French)

- lib/providers/source_provider.dart
- pubspec.yaml
Catch errors when running JSON compat mods - app breaking bug (#2015, #2019)
> Catch errors when running JSON compat mods - app breaking bug (#2015, #2019)

- assets/translations/en.json
Closes #2209
This PR updates the setting label from:
- "Auto-export on changes"
to:
- "Automatically export on changes"
Improves readability and aligns with consistent naming conventions.
- Verified the label change in the UI
- No functional impact, purely a text update
> fix: automatically export on changes (#2209)

- lib/app_sources/html.dart
Fixes #2272
I went through the Git history for the HTML app source to find all of the commits where the `ensureAbsoluteUrl` function was modified, and the related issues/discussions. As far as I can see this PR will not cause any regressions.
I also created a test script to verify that the built-in `resolve()` method works as expected. The script also shows that there are various cases that the current custom implementation does not handle correctly.
```dart
String ensureAbsoluteUrl(String ambiguousUrl, Uri referenceAbsoluteUrl) {
if (ambiguousUrl.startsWith('//')) {
ambiguousUrl = '${referenceAbsoluteUrl.scheme}:$ambiguousUrl';
}
try {
Uri.parse(ambiguousUrl).origin;
return ambiguousUrl;
} catch (err) {
// is relative
}
var currPathSegments = referenceAbsoluteUrl.path
.split('/') …
```
> Use built-in method to fix HTML link resolution

- lib/app_sources/apkpure.dart
I'm really sorry, but apparently a really stupid bug slipped into my code in #2290 resulting in invalid version codes (last digit was cut off). I only tested if i could add and see the new versions not if the download was actually working.
The bug is now fixed and I tested it completely this time. (both adding and downloading an app)
> bugfix: invalid version codes for some apkpure links

- .dockerignore
- .gitignore
- docker/Dockerfile
- docker/builder.sh
- docker/mkbuilder.sh
When developing on a remote `code-server`, it is common practice to have a remote build environment specific to the application. This PR provides a set of scripts that allow developers to set up this environment.
On the host
```bash
./docker/mkbuilder.sh
./docker/builder.sh
```
Now that you're in the running container:
```bash
adb connect localhost:7775
flutter run --flavor normal
```
Exiting the container will remove it.
> Add support for building via a docker container [remote dev]

- assets/translations/ca.json
- assets/translations/cs.json
- assets/translations/da.json
- assets/translations/en-EO.json
- assets/translations/en.json
- assets/translations/fr.json
- assets/translations/pt.json
- assets/translations/sv.json
- assets/translations/tr.json
- assets/translations/vi.json
addresses #2418. many languages already did this.
as i checked, the settings slider for update interval is the only place where these strings are used. i updated i18n files where i was sure to change it (because of that, i skipped `de.json`).
> Use lowercase in settings slider
